### ISSUE TITLE
Update used docker image to Ubuntu 22.04

### ISSUE THREAD

**Issue by lieser** [microwalk-project/microwalk-pin-action#1]
As a test I'm currently trying to integrate a Microwalk CI to [Botan](https://github.com/randombit/botan).

The latest Botan 3.0.0 release needs C++20 and officially supports GCC >= 11 and Clang >= 14. Unfortunately the currently used image for this action seems to be based on Ubuntu focal (20.04) which has only older versions of GCC and Clang.

- Would it be possible to update the default docker image used in this action to a newer one?
- Is there an easy way to specify a different base image that I may have missed?

**Comment by JanWichelmann** [comment]
At the moment the only available image is indeed based on Ubuntu 20.04. I am working on an updated image featuring Ubuntu 22.04, but need to some more tests to ensure that nothing breaks - this may take at most a few days.

**Comment by JanWichelmann** [comment]
Good news, everything went rather smooth, and the images now feature Ubuntu 22.04 and the newest Pin 3.27. I've also done some other bugfixes/improvements to the CI workflow.

I've also prepared an example of how to integrate Microwalk into the WolfSSL library: https://github.com/microwalk-project/wolfssl-demo/tree/microwalk  
This may be a good starting point for using Microwalk with Botan.

Please let me know if you need help or have any questions!

**Comment by lieser** [comment]
Thanks for the quick update. Now the analyze runs, so I think this issue can be closed as at least the tool chain problem is solved.

I however get a lot of warnings (https://github.com/lieser/botan/actions/runs/4701855851/jobs/8338408892).

A few trace messages similar to:
```
[dbug] [trace:pin] Pin tool log: Error: Cannot resolve image of basic block 7fa6a0631220 (instrumenting as 'interesting')
```

A lot of warnings similar to:
```
[warn] [preprocess:prefix] Free of address 00005629e46ad420 does not correspond to any heap allocation, skipping
```

A massive amount of message similar to
```
[warn] [preprocess:0] Could not resolve target of memory access 00007fa6a100af38 -> [00005629e46a4a88] (read), skipping
[warn] [preprocess:0] Could not resolve target of memory access 00007fa6a0f0070e -> [00005629e4697170] (write), skipping
```

For a pretty small test the complete log is over 1.000.000 lines long, which does not seem normal to me.

Would be nice if you can give me a hint on what is going wrong. Let me know if I should open an issue in the main repository for this usage question.

**Comment by JanWichelmann** [comment]
Yeah, lets move this to the main repository. Could you repost there?

I will look into the warnings in the meantime :-)
